[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#f3f4f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "sans serif"
base = "light"

[browser]
gatherUsageStats = false
